language: generic
before_install:
- mkdir $HOME/.fonts
- cp -a $TRAVIS_BUILD_DIR/fonts/. $HOME/.fonts/
- fc-cache -f -v
install:
- source ./texlive/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR/
script:
- texliveonfly codebook.tex --compiler=xelatex
- latexmk -pdfxe codebook.tex
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
  - ./codebook.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email: false