name: codebook

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'codebook.pdf'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'codebook.pdf'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull codebook-builder
        run: docker pull docker.io/fjuonlinejudge/codebook-builder

      - name: Build codebook (XeLaTeX)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/storage \
            docker.io/fjuonlinejudge/codebook-builder \
            bash -c "xelatex /storage/codebook.tex && xelatex /storage/codebook.tex"

      - name: Move codebook.pdf
        run: |
          mkdir tmp
          mv codebook.pdf tmp
          git checkout pdf || git checkout -b pdf
          mv tmp/codebook.pdf .

      - name: Push codebook
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: pdf
          commit_message: auto build codebook.pdf
          file_pattern: codebook.pdf