name: codebook

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
     - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
     - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull codebook-builder
        run: docker pull ghcr.io/hjackh/codebook-builder:latest
        
      - name: Build codebook
        run: |
          docker run --rm -v $(pwd):/storage ghcr.io/hjackh/codebook-builder \
          /bin/bash -c "texliveonfly codebook.tex --compiler=xelatex ; latexmk -pdfxe codebook.tex"
      - name: Move codebook.pdf
        run: |
          mkdir tmp
          mv codebook.pdf tmp
          git checkout gh-pages
          mv tmp/codebook.pdf .
      - name: Commit
        run: |
          timedatectl set-timezone "Asia/Taipei"
          git config --local user.email ${{ secrets.GH_EMAIL }}
          git config --local user.name ${{ github.repository_owner }}
          git add codebook.pdf
          git commit -m "Built on: `date +'%Y-%m-%d-%T'`"
      - name: Push codebook
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages